-- Align enums with schema
ALTER TYPE "LedgerCategory" ADD VALUE IF NOT EXISTS 'STAFF_PAYOUT';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'UZUM';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ACCOUNTANT';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'KASSIR';

-- Align User table columns present in schema but missing from migration history
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "position" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "passportPinfl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hiredAt" DATE;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "salaryUzs" INTEGER;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastSalaryPaidAt" TIMESTAMP(3);
